// src/App.tsx
import { RouterProvider, createRouter } from '@tanstack/react-router'
import {
  useQuery,
  useMutation,
  useQueryClient,
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query'
import { routeTree } from './routeTree.gen' // Auto-generated by TanStack

const queryClient = new QueryClient();
const router = createRouter({
  routeTree,
  context: {
    auth: undefined!, // This will be set by the Provider below
  },
});

// Register the router for maximum type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

export default function App() {
  // const auth = useAuth() // Get current user and role from your state

  return (
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} context={{ auth: {user: 'home'} }} />
    </QueryClientProvider>
  )
}