name: dbms
services:
  # react-prod:
  #   build:
  #     context: .
  #     dockerfile: .docker/prod/Dockerfile
  #   image: docker-reactjs-sample
  #   ports:
  #     - "8080:8080"

  ui_dev:
    build:
      context: app_ui
      dockerfile: .docker/dev/Dockerfile
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: app_ui
          target: /app
    depends_on:
      - backend_dev
  backend_dev:
    build: 
      context: app_backend
      dockerfile: .docker/dev/Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Все ще потрібні змінні для надійності
      - PYTHONPATH=/app/src
      - WATCHFILES_FORCE_POLLING=true 
      - UV_NO_DEV=0
      - DB_USER=user
      - DB_PASSWORD=mysecretpassword
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=dbms_app
      - PG_COLOR=always
      
    # Використовуємо volumes замість develop/watch
    volumes:
      # Монтуємо вашу локальну папку src до цільової папки в контейнері
      - ./app_backend/src:/app/src
      # Якщо ви використовуєте .venv локально, його теж треба змонтувати, щоб не було конфліктів
      - ./app_backend/.venv:/app/.venv 
      - .psqlrc:/var/lib/postgresql/.psqlrc
    depends_on:
      - db
    stdin_open: true
    tty: true
    # Команда, яка запускає hot-reload
    command: uv run fastapi dev src/main.py --host 0.0.0.0 --port 8000
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: dbms_app
    ports:
      - "5454:5432"
    volumes:
      - db_data:/var/lib/postgresql
volumes:
  db_data: