/**
 * Utility functions for PostgreSQL Configuration components
 */

import { Settings, HardDrive, Network, Database, Zap, FileText, Cpu } from 'lucide-react';
import type { ConfigParam, ConfigStatistics, ConfigCategory } from './types';

/**
 * Get icon component for configuration category
 */
export const getCategoryIcon = (category: string) => {
  switch (category) {
    case 'memory':
      return HardDrive;
    case 'connections':
      return Network;
    case 'wal':
      return Database;
    case 'autovacuum':
      return Zap;
    case 'logging':
      return FileText;
    case 'performance':
      return Cpu;
    default:
      return Settings;
  }
};

/**
 * Get display name for configuration category
 */
export const getCategoryName = (category: string): string => {
  const names: Record<string, string> = {
    memory: 'Пам\'ять',
    connections: 'Підключення',
    wal: 'WAL',
    autovacuum: 'Autovacuum',
    logging: 'Логування',
    performance: 'Продуктивність',
  };
  return names[category] || category;
};

/**
 * Get gradient color classes for category
 */
export const getCategoryColor = (category: string): string => {
  const colors: Record<string, string> = {
    memory: 'from-lime-500 to-green-600',
    connections: 'from-green-500 to-lime-600',
    wal: 'from-yellow-500 to-lime-600',
    autovacuum: 'from-lime-600 to-yellow-600',
    logging: 'from-green-600 to-lime-500',
    performance: 'from-lime-500 to-green-500',
  };
  return colors[category] || 'from-slate-500 to-slate-600';
};

/**
 * Calculate configuration statistics
 */
export const calculateStatistics = (params: ConfigParam[]): ConfigStatistics => {
  return {
    totalParams: params.length,
    changed: params.filter(p => p.value !== p.defaultValue).length,
    requiresRestart: params.filter(p => p.requiresRestart && p.value !== p.defaultValue).length,
  };
};

/**
 * Get unique categories from config parameters
 */
export const getCategories = (params: ConfigParam[]): string[] => {
  return Array.from(new Set(params.map(p => p.category)));
};

/**
 * Filter parameters by category
 */
export const getParamsByCategory = (params: ConfigParam[], category: string): ConfigParam[] => {
  return params.filter(p => p.category === category);
};

/**
 * Generate postgresql.conf file content
 */
export const generateConfigFile = (params: ConfigParam[]): string => {
  const groupedByCategory: Record<string, ConfigParam[]> = {};
  
  params.forEach(param => {
    if (!groupedByCategory[param.category]) {
      groupedByCategory[param.category] = [];
    }
    groupedByCategory[param.category].push(param);
  });

  let config = `# PostgreSQL Configuration File
# Generated by PostgreSQL DBMS Admin Panel
# Date: ${new Date().toISOString().split('T')[0]}
`;

  const categoryHeaders: Record<string, string> = {
    memory: 'MEMORY SETTINGS',
    connections: 'CONNECTION SETTINGS',
    wal: 'WRITE-AHEAD LOG (WAL)',
    autovacuum: 'AUTOVACUUM',
    logging: 'LOGGING',
    performance: 'QUERY TUNING / PERFORMANCE',
  };

  Object.entries(groupedByCategory).forEach(([category, categoryParams]) => {
    config += `
#------------------------------------------------------------------------------
# ${categoryHeaders[category] || category.toUpperCase()}
#------------------------------------------------------------------------------
`;
    categoryParams.forEach(param => {
      config += `${param.name} = ${param.value}\n`;
    });
  });

  return config;
};

/**
 * Export configuration as JSON
 */
export const exportConfigAsJSON = (params: ConfigParam[], profileName: string = 'config'): void => {
  const config = {
    name: profileName,
    generatedAt: new Date().toISOString(),
    parameters: params.reduce((acc, param) => {
      acc[param.name] = param.value;
      return acc;
    }, {} as Record<string, string>),
  };

  const blob = new Blob([JSON.stringify(config, null, 2)], {
    type: 'application/json',
  });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `postgresql-config-${Date.now()}.json`;
  link.click();
  URL.revokeObjectURL(url);
};

/**
 * Export configuration as .conf file
 */
export const exportConfigAsFile = (params: ConfigParam[]): void => {
  const content = generateConfigFile(params);
  
  const blob = new Blob([content], {
    type: 'text/plain',
  });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `postgresql-${Date.now()}.conf`;
  link.click();
  URL.revokeObjectURL(url);
};

/**
 * Validate configuration parameter value
 */
export const validateParamValue = (param: ConfigParam, value: string): {
  valid: boolean;
  error?: string;
} => {
  // Basic validation - can be extended
  if (!value || value.trim() === '') {
    return { valid: false, error: 'Значення не може бути порожнім' };
  }

  // Validate numeric values
  if (param.unit && !value.match(/^\d+[A-Za-z]*$/)) {
    return { valid: false, error: 'Неправильний формат значення' };
  }

  // Validate boolean values
  if (['on', 'off'].includes(param.defaultValue)) {
    if (!['on', 'off'].includes(value)) {
      return { valid: false, error: 'Значення має бути "on" або "off"' };
    }
  }

  return { valid: true };
};

/**
 * Parse .conf file content
 */
export const parseConfigFile = (content: string): Record<string, string> => {
  const config: Record<string, string> = {};
  const lines = content.split('\n');

  lines.forEach(line => {
    // Skip comments and empty lines
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;

    // Parse parameter = value
    const match = trimmed.match(/^([a-z_]+)\s*=\s*(.+)$/);
    if (match) {
      const [, key, value] = match;
      config[key] = value.trim();
    }
  });

  return config;
};

/**
 * Check if parameter has been modified
 */
export const isParamModified = (param: ConfigParam): boolean => {
  return param.value !== param.defaultValue;
};

/**
 * Get preset configuration by type
 */
export const getPresetConfig = (presetType: 'development' | 'production' | 'highload'): Record<string, string> => {
  const presets = {
    development: {
      shared_buffers: '128MB',
      work_mem: '4MB',
      max_connections: '50',
      logging_collector: 'on',
      log_min_duration_statement: '0',
      log_connections: 'on',
      log_disconnections: 'on',
    },
    production: {
      shared_buffers: '512MB',
      work_mem: '16MB',
      max_connections: '200',
      max_wal_size: '4GB',
      logging_collector: 'on',
      log_min_duration_statement: '1000',
      random_page_cost: '1.1',
      effective_io_concurrency: '200',
    },
    highload: {
      shared_buffers: '1GB',
      work_mem: '32MB',
      max_connections: '500',
      max_wal_size: '8GB',
      effective_cache_size: '8GB',
      random_page_cost: '1.0',
      effective_io_concurrency: '300',
      autovacuum_max_workers: '6',
    },
  };

  return presets[presetType] || {};
};

/**
 * Compare two configurations
 */
export const compareConfigs = (
  config1: Record<string, string>,
  config2: Record<string, string>
): {
  same: string[];
  different: string[];
  onlyInFirst: string[];
  onlyInSecond: string[];
} => {
  const allKeys = new Set([...Object.keys(config1), ...Object.keys(config2)]);
  const result = {
    same: [] as string[],
    different: [] as string[],
    onlyInFirst: [] as string[],
    onlyInSecond: [] as string[],
  };

  allKeys.forEach(key => {
    if (config1[key] && config2[key]) {
      if (config1[key] === config2[key]) {
        result.same.push(key);
      } else {
        result.different.push(key);
      }
    } else if (config1[key]) {
      result.onlyInFirst.push(key);
    } else {
      result.onlyInSecond.push(key);
    }
  });

  return result;
};

/**
 * Format file size for display
 */
export const formatFileSize = (bytes: number): string => {
  const units = ['B', 'KB', 'MB', 'GB', 'TB'];
  let size = bytes;
  let unitIndex = 0;

  while (size >= 1024 && unitIndex < units.length - 1) {
    size /= 1024;
    unitIndex++;
  }

  return `${size.toFixed(2)} ${units[unitIndex]}`;
};

/**
 * Estimate memory usage from configuration
 */
export const estimateMemoryUsage = (params: ConfigParam[]): number => {
  let totalMB = 0;

  params.forEach(param => {
    if (param.category === 'memory' && param.unit) {
      const value = parseFloat(param.value);
      if (param.unit === 'GB') {
        totalMB += value * 1024;
      } else if (param.unit === 'MB') {
        totalMB += value;
      }
    }
  });

  return totalMB;
};
