// PostgreSQL Configuration Mock Data

export interface ConfigSetting {
  name: string;
  value: string;
  unit?: string;
  category: string;
  description: string;
  requiresRestart: boolean;
  context: string;
}

export const postgresConfigSettings: ConfigSetting[] = [
  {
    name: 'max_connections',
    value: '200',
    unit: '',
    category: 'Connections and Authentication',
    description: 'Максимальна кількість одночасних підключень до сервера',
    requiresRestart: true,
    context: 'postmaster',
  },
  {
    name: 'shared_buffers',
    value: '2048',
    unit: 'MB',
    category: 'Resource Usage (Memory)',
    description: 'Розмір загальної пам\'яті для кешування даних',
    requiresRestart: true,
    context: 'postmaster',
  },
  {
    name: 'effective_cache_size',
    value: '8192',
    unit: 'MB',
    category: 'Query Tuning',
    description: 'Припущення планувальника щодо розміру кешу ОС',
    requiresRestart: false,
    context: 'user',
  },
  {
    name: 'work_mem',
    value: '16',
    unit: 'MB',
    category: 'Resource Usage (Memory)',
    description: 'Пам\'ять для внутрішніх операцій сортування та хешування',
    requiresRestart: false,
    context: 'user',
  },
  {
    name: 'maintenance_work_mem',
    value: '512',
    unit: 'MB',
    category: 'Resource Usage (Memory)',
    description: 'Пам\'ять для операцій обслуговування (VACUUM, CREATE INDEX)',
    requiresRestart: false,
    context: 'user',
  },
  {
    name: 'wal_buffers',
    value: '16',
    unit: 'MB',
    category: 'Write-Ahead Log',
    description: 'Розмір буферів для WAL (Write-Ahead Log)',
    requiresRestart: true,
    context: 'postmaster',
  },
  {
    name: 'checkpoint_completion_target',
    value: '0.9',
    unit: '',
    category: 'Write-Ahead Log',
    description: 'Час завершення checkpoint як частина від checkpoint_timeout',
    requiresRestart: false,
    context: 'sighup',
  },
  {
    name: 'max_wal_size',
    value: '4',
    unit: 'GB',
    category: 'Write-Ahead Log',
    description: 'Максимальний розмір WAL між автоматичними checkpoint',
    requiresRestart: false,
    context: 'sighup',
  },
  {
    name: 'min_wal_size',
    value: '1',
    unit: 'GB',
    category: 'Write-Ahead Log',
    description: 'Мінімальний розмір WAL для утримання',
    requiresRestart: false,
    context: 'sighup',
  },
  {
    name: 'random_page_cost',
    value: '1.1',
    unit: '',
    category: 'Query Tuning',
    description: 'Вартість читання випадкової сторінки диску',
    requiresRestart: false,
    context: 'user',
  },
  {
    name: 'effective_io_concurrency',
    value: '200',
    unit: '',
    category: 'Query Tuning',
    description: 'Кількість одночасних операцій вводу-виводу',
    requiresRestart: false,
    context: 'user',
  },
  {
    name: 'max_worker_processes',
    value: '8',
    unit: '',
    category: 'Resource Usage (Asynchronous Behavior)',
    description: 'Максимальна кількість фонових процесів',
    requiresRestart: true,
    context: 'postmaster',
  },
  {
    name: 'max_parallel_workers_per_gather',
    value: '4',
    unit: '',
    category: 'Resource Usage (Asynchronous Behavior)',
    description: 'Максимальна кількість паралельних воркерів для одного вузла Gather',
    requiresRestart: false,
    context: 'user',
  },
  {
    name: 'max_parallel_workers',
    value: '8',
    unit: '',
    category: 'Resource Usage (Asynchronous Behavior)',
    description: 'Максимальна кількість паралельних воркерів',
    requiresRestart: false,
    context: 'user',
  },
  {
    name: 'log_destination',
    value: 'stderr',
    unit: '',
    category: 'Error Reporting and Logging',
    description: 'Куди відправляти лог-повідомлення',
    requiresRestart: false,
    context: 'sighup',
  },
  {
    name: 'logging_collector',
    value: 'on',
    unit: '',
    category: 'Error Reporting and Logging',
    description: 'Чи збирати лог-файли у фоновому процесі',
    requiresRestart: true,
    context: 'postmaster',
  },
  {
    name: 'log_min_duration_statement',
    value: '1000',
    unit: 'ms',
    category: 'Error Reporting and Logging',
    description: 'Логувати запити, що виконуються довше зазначеного часу',
    requiresRestart: false,
    context: 'superuser',
  },
  {
    name: 'autovacuum',
    value: 'on',
    unit: '',
    category: 'Autovacuum',
    description: 'Чи запускати процес autovacuum',
    requiresRestart: false,
    context: 'sighup',
  },
  {
    name: 'autovacuum_max_workers',
    value: '3',
    unit: '',
    category: 'Autovacuum',
    description: 'Максимальна кількість процесів autovacuum',
    requiresRestart: true,
    context: 'postmaster',
  },
  {
    name: 'autovacuum_naptime',
    value: '60',
    unit: 's',
    category: 'Autovacuum',
    description: 'Час між запусками autovacuum',
    requiresRestart: false,
    context: 'sighup',
  },
];

export const configCategories = [
  'Connections and Authentication',
  'Resource Usage (Memory)',
  'Resource Usage (Asynchronous Behavior)',
  'Write-Ahead Log',
  'Query Tuning',
  'Error Reporting and Logging',
  'Autovacuum',
  'Client Connection Defaults',
  'Lock Management',
  'Version and Platform Compatibility',
];
