/**
 * Configuration file generation functions
 */

import type { ConfigParam } from '../types';

/**
 * Generate postgresql.conf file content
 */
export const generateConfigFile = (params: ConfigParam[]): string => {
  const groupedByCategory: Record<string, ConfigParam[]> = {};
  
  params.forEach(param => {
    if (!groupedByCategory[param.category]) {
      groupedByCategory[param.category] = [];
    }
    groupedByCategory[param.category].push(param);
  });

  let config = `# PostgreSQL Configuration File
# Generated by PostgreSQL DBMS Admin Panel
# Date: ${new Date().toISOString().split('T')[0]}
`;

  const categoryHeaders: Record<string, string> = {
    memory: 'MEMORY SETTINGS',
    connections: 'CONNECTION SETTINGS',
    wal: 'WRITE-AHEAD LOG (WAL)',
    autovacuum: 'AUTOVACUUM',
    logging: 'LOGGING',
    performance: 'QUERY TUNING / PERFORMANCE',
  };

  Object.entries(groupedByCategory).forEach(([category, categoryParams]) => {
    config += `
#------------------------------------------------------------------------------
# ${categoryHeaders[category] || category.toUpperCase()}
#------------------------------------------------------------------------------
`;
    categoryParams.forEach(param => {
      config += `${param.name} = ${param.value}\n`;
    });
  });

  return config;
};
