import type { DashboardDatabase } from './types';

// Dashboard Databases - бази даних для grid view на dashboard (з правами та ролями)
export const dashboardDatabases: DashboardDatabase[] = [
  {
    id: 1,
    name: 'crm_database',
    tables: 24,
    records: 12947,
    lastAccess: '5 хвилин тому',
    permissions: ['SELECT', 'INSERT', 'UPDATE'],
    grantedByRoles: ['Developer', 'Data Analyst'],
    color: 'from-violet-500 to-purple-600',
  },
  {
    id: 2,
    name: 'project_management',
    tables: 18,
    records: 18234,
    lastAccess: '15 хвилин тому',
    permissions: ['SELECT', 'INSERT', 'UPDATE', 'DELETE'],
    grantedByRoles: ['Developer', 'Content Manager'],
    color: 'from-blue-500 to-cyan-600',
  },
  {
    id: 3,
    name: 'analytics_db',
    tables: 12,
    records: 4567,
    lastAccess: '1 годину тому',
    permissions: ['SELECT'],
    grantedByRoles: ['Data Analyst', 'Viewer'],
    color: 'from-indigo-500 to-violet-600',
  },
  {
    id: 4,
    name: 'ecommerce_db',
    tables: 32,
    records: 35923,
    lastAccess: '3 години тому',
    permissions: ['SELECT', 'INSERT', 'UPDATE'],
    grantedByRoles: ['Developer', 'Content Manager'],
    color: 'from-green-500 to-lime-600',
  },
  {
    id: 5,
    name: 'content_db',
    tables: 15,
    records: 8234,
    lastAccess: '5 годин тому',
    permissions: ['SELECT', 'INSERT', 'UPDATE'],
    grantedByRoles: ['Content Manager'],
    color: 'from-pink-500 to-rose-600',
  },
  {
    id: 6,
    name: 'reports_db',
    tables: 8,
    records: 1245,
    lastAccess: '1 день тому',
    permissions: ['SELECT'],
    grantedByRoles: ['Data Analyst', 'Viewer'],
    color: 'from-amber-500 to-orange-600',
  },
];
