from typing import List
from app_admin.ui.pages.pg_config.params.schema import PgConfigParam
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from src.core import dependencies  # Dependency for DB session



pg_config_params_router = APIRouter()

@pg_config_params_router.get("/", response_model=List[PgConfigParam])
def get_pg_config_params(db: Session = Depends(dependencies.get_db)):
    # Тут має бути логіка отримання активних з'єднань з бази даних
    # Поки що повертаємо фіктивні дані для прикладу
    return [
        {
            "name": "autovacuum",
            "value": "on",
            "default_value": "on",
            "description": "Автоматичне очищення (vacuum) таблиць",
            "requires_restart": False,
            "category": "autovacuum",
        },
        {
            "name": "autovacuum_max_workers",
            "value": "3",
            "default_value": "3",
            "description": "Максимальна кількість процесів autovacuum",
            "requires_restart": True,
            "category": "autovacuum",
        },
        {
            "name": "autovacuum_naptime",
            "value": "60s",
            "default_value": "1min",
            "description": "Час між запусками autovacuum",
            "requires_restart": False,
            "category": "autovacuum",
        },
        {
            "name": "max_connections",
            "value": "200",
            "default_value": "100",
            "description": "Максимальна кількість одночасних підключень",
            "requires_restart": True,
            "category": "connections",
        },
        {
            "name": "superuser_reserved_connections",
            "value": "5",
            "default_value": "3",
            "description": "Резервні підключення для суперкористувачів",
            "requires_restart": True,
            "category": "connections",
        },
        {
            "name": "idle_in_transaction_session_timeout",
            "value": "30000",
            "default_value": "0",
            "unit": "ms",
            "description": "Таймаут для неактивних транзакцій",
            "requires_restart": False,
            "category": "connections",
        },
        {
            "name": "logging_collector",
            "value": "on",
            "default_value": "off",
            "description": "Збір логів у фонові файли",
            "requires_restart": True,
            "category": "logging",
        },
        {
            "name": "log_min_duration_statement",
            "value": "1000",
            "default_value": "-1",
            "unit": "ms",
            "description": "Логувати запити довші за вказаний час",
            "requires_restart": False,
            "category": "logging",
        },
        {
            "name": "log_checkpoints",
            "value": "on",
            "default_value": "off",
            "description": "Логувати контрольні точки",
            "requires_restart": False,
            "category": "logging",
        },
        {
            "name": "log_connections",
            "value": "on",
            "default_value": "off",
            "description": "Логувати нові підключення",
            "requires_restart": False,
            "category": "logging",
        },
        {
            "name": "log_disconnections",
            "value": "on",
            "default_value": "off",
            "description": "Логувати відключення",
            "requires_restart": False,
            "category": "logging",
        },
        {
            "name": "shared_buffers",
            "value": "256MB",
            "default_value": "128MB",
            "unit": "MB",
            "description": "Обсяг пам'яті для кешування даних",
            "requires_restart": True,
            "category": "memory",
        },
        {
            "name": "work_mem",
            "value": "8MB",
            "default_value": "4MB",
            "unit": "MB",
            "description": "Пам'ять для операцій сортування та хешування",
            "requires_restart": False,
            "category": "memory",
        },
        {
            "name": "maintenance_work_mem",
            "value": "128MB",
            "default_value": "64MB",
            "unit": "MB",
            "description": "Пам'ять для операцій обслуговування (VACUUM, CREATE INDEX)",
            "requires_restart": False,
            "category": "memory",
        },
        {
            "name": "effective_cache_size",
            "value": "1GB",
            "default_value": "4GB",
            "unit": "GB",
            "description": "Оцінка доступної пам'яті для кешування ОС",
            "requires_restart": False,
            "category": "memory",
        },
        {
            "name": "random_page_cost",
            "value": "1.1",
            "default_value": "4.0",
            "description": "Вартість випадкового читання сторінки (для SSD)",
            "requires_restart": False,
            "category": "performance",
        },
        {
            "name": "effective_io_concurrency",
            "value": "200",
            "default_value": "1",
            "description": "Паралельність I/O операцій (для SSD)",
            "requires_restart": False,
            "category": "performance",
        },
        {
            "name": "default_statistics_target",
            "value": "100",
            "default_value": "100",
            "description": "Ціль для збору статистики планувальника",
            "requires_restart": False,
            "category": "performance",
        },
        {
            "name": "wal_level",
            "value": "replica",
            "default_value": "replica",
            "description": "Рівень деталізації WAL логів",
            "requires_restart": True,
            "category": "wal",
        },
        {
            "name": "max_wal_size",
            "value": "2GB",
            "default_value": "1GB",
            "unit": "GB",
            "description": "Максимальний розмір WAL між checkpoint",
            "requires_restart": False,
            "category": "wal",
        },
        {
            "name": "min_wal_size",
            "value": "512MB",
            "default_value": "80MB",
            "unit": "MB",
            "description": "Мінімальний розмір WAL",
            "requires_restart": False,
            "category": "wal",
        },
        {
            "name": "wal_buffers",
            "value": "16MB",
            "default_value": "-1",
            "unit": "MB",
            "description": "Буфери для WAL даних",
            "requires_restart": True,
            "category": "wal",
        },
    ]