import { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '../../../ui/dialog';
import { Button } from '../../../ui/button';
import { Input } from '../../../ui/input';
import { Label } from '../../../ui/label';
import { Textarea } from '../../../ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '../../../ui/select';
import { Switch } from '../../../ui/switch';
import { Loader2, AlertCircle } from 'lucide-react';
import { Alert, AlertDescription } from '../../../ui/alert';
import type { ColumnSchema } from './types';

interface AddRecordModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  tableName: string;
  schema: ColumnSchema[];
  onAddRecord: (data: Record<string, any>) => Promise<void>;
}

export default function AddRecordModal({
  open,
  onOpenChange,
  tableName,
  schema,
  onAddRecord,
}: AddRecordModalProps) {
  const [formData, setFormData] = useState<Record<string, any>>({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Reset form when modal opens/closes
  const handleOpenChange = (isOpen: boolean) => {
    if (!isOpen) {
      setFormData({});
      setError(null);
    }
    onOpenChange(isOpen);
  };

  // Get input type based on column type
  const getInputType = (columnType: string): string => {
    const lowerType = columnType.toLowerCase();
    if (lowerType.includes('int') || lowerType.includes('serial')) return 'number';
    if (lowerType.includes('decimal') || lowerType.includes('numeric') || lowerType.includes('float')) return 'number';
    if (lowerType.includes('bool')) return 'checkbox';
    if (lowerType.includes('date') && !lowerType.includes('time')) return 'date';
    if (lowerType.includes('time')) return 'datetime-local';
    if (lowerType.includes('text')) return 'textarea';
    return 'text';
  };

  // Check if field should have a default value
  const hasAutoDefault = (column: ColumnSchema): boolean => {
    const defaultVal = column.default?.toLowerCase() || '';
    return (
      defaultVal.includes('nextval()') ||
      defaultVal.includes('current_timestamp') ||
      defaultVal.includes('now()') ||
      (column.key === 'PRI' && defaultVal.includes('nextval'))
    );
  };

  // Handle form field change
  const handleFieldChange = (columnName: string, value: any) => {
    setFormData((prev) => ({
      ...prev,
      [columnName]: value,
    }));
  };

  // Validate form
  const validateForm = (): boolean => {
    setError(null);

    // Check required fields
    for (const column of schema) {
      // Skip auto-generated fields
      if (hasAutoDefault(column)) continue;

      // Check if required field is empty
      if (!column.nullable && !formData[column.column]) {
        setError(`Поле "${column.column}" є обов'язковим`);
        return false;
      }
    }

    return true;
  };

  // Handle form submission
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!validateForm()) return;

    setIsSubmitting(true);
    setError(null);

    try {
      await onAddRecord(formData);
      handleOpenChange(false);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Помилка при додаванні запису');
    } finally {
      setIsSubmitting(false);
    }
  };

  // Render input field based on column type
  const renderField = (column: ColumnSchema) => {
    const inputType = getInputType(column.type);
    const isAutoGenerated = hasAutoDefault(column);
    const value = formData[column.column] || '';

    // Auto-generated fields (show as disabled)
    if (isAutoGenerated) {
      return (
        <div className="space-y-2">
          <Label htmlFor={column.column} className="text-slate-600">
            {column.column}
            <span className="ml-2 text-xs text-slate-400">(автоматично)</span>
          </Label>
          <Input
            id={column.column}
            disabled
            placeholder={column.default || 'Генерується автоматично'}
            className="bg-slate-50"
          />
        </div>
      );
    }

    // Boolean/Checkbox
    if (inputType === 'checkbox') {
      return (
        <div className="flex items-center justify-between space-x-2 py-2">
          <Label htmlFor={column.column} className="text-slate-700">
            {column.column}
            {!column.nullable && <span className="text-red-500 ml-1">*</span>}
          </Label>
          <Switch
            id={column.column}
            checked={!!value}
            onCheckedChange={(checked) => handleFieldChange(column.column, checked)}
          />
        </div>
      );
    }

    // Textarea for text columns
    if (inputType === 'textarea') {
      return (
        <div className="space-y-2">
          <Label htmlFor={column.column} className="text-slate-700">
            {column.column}
            {!column.nullable && <span className="text-red-500 ml-1">*</span>}
            <span className="ml-2 text-xs text-slate-400">{column.type}</span>
          </Label>
          <Textarea
            id={column.column}
            value={value}
            onChange={(e) => handleFieldChange(column.column, e.target.value)}
            placeholder={column.nullable ? 'Необов\'язково' : ''}
            rows={3}
            className="resize-none"
          />
        </div>
      );
    }

    // Select for enum/status fields
    if (column.column.toLowerCase().includes('status') && column.type.includes('varchar')) {
      const options = getStatusOptions(column.column, column.default);
      return (
        <div className="space-y-2">
          <Label htmlFor={column.column} className="text-slate-700">
            {column.column}
            {!column.nullable && <span className="text-red-500 ml-1">*</span>}
            <span className="ml-2 text-xs text-slate-400">{column.type}</span>
          </Label>
          <Select
            value={value}
            onValueChange={(val) => handleFieldChange(column.column, val)}
          >
            <SelectTrigger>
              <SelectValue placeholder="Оберіть статус" />
            </SelectTrigger>
            <SelectContent>
              {options.map((option) => (
                <SelectItem key={option} value={option}>
                  {option}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      );
    }

    // Regular input fields
    return (
      <div className="space-y-2">
        <Label htmlFor={column.column} className="text-slate-700">
          {column.column}
          {!column.nullable && <span className="text-red-500 ml-1">*</span>}
          <span className="ml-2 text-xs text-slate-400">{column.type}</span>
        </Label>
        <Input
          id={column.column}
          type={inputType}
          step={inputType === 'number' && column.type.includes('decimal') ? '0.01' : undefined}
          value={value}
          onChange={(e) => handleFieldChange(column.column, e.target.value)}
          placeholder={column.nullable ? 'Необов\'язково' : ''}
        />
      </div>
    );
  };

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Додати новий запис</DialogTitle>
          <DialogDescription>
            Додати новий запис до таблиці <strong>{tableName}</strong>
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-4">
          {error && (
            <Alert variant="destructive">
              <AlertCircle className="h-4 w-4" />
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}

          <div className="space-y-4 py-4">
            {schema.map((column) => (
              <div key={column.column}>{renderField(column)}</div>
            ))}
          </div>

          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              onClick={() => handleOpenChange(false)}
              disabled={isSubmitting}
            >
              Скасувати
            </Button>
            <Button type="submit" disabled={isSubmitting} className="bg-olive-600 hover:bg-olive-700">
              {isSubmitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
              Додати запис
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

// Helper function to get status options
function getStatusOptions(columnName: string, defaultValue: string | null): string[] {
  const lower = columnName.toLowerCase();
  
  if (lower === 'status') {
    // Extract default from string like "'active'"
    const def = defaultValue?.replace(/'/g, '');
    return def === 'active' 
      ? ['active', 'inactive', 'suspended', 'pending']
      : def === 'pending'
      ? ['pending', 'processing', 'completed', 'cancelled', 'shipped']
      : ['pending', 'active', 'completed', 'cancelled'];
  }
  
  return ['active', 'inactive'];
}
