// src/App.tsx
import { RouterProvider, createRouter } from '@tanstack/react-router'
import { routeTree } from './routeTree.gen' // Auto-generated by TanStack

// Create the router instance outside the component
const router = createRouter({
  routeTree,
  context: {
    auth: undefined!, // This will be set by the Provider below
  },
})

// Register the router for maximum type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

export default function App() {
  // const auth = useAuth() // Get current user and role from your state

  // Provide the router and current auth state to the application
  return <RouterProvider router={router} context={{ auth: {user: 'home'} }} />
}


