import type { Database } from './types';

// E-commerce Database - електронна комерція
export const ecommerceDatabase: Database = {
  id: 4,
  name: 'ecommerce_db',
  description: 'Електронна комерція',
  tables: [
    {
      name: 'products',
      records: 8921,
      size: '12.4 MB',
      permissions: ['SELECT', 'INSERT', 'UPDATE'],
      rlsEnabled: false,
      description: 'Каталог товарів',
    },
    {
      name: 'orders',
      records: 12456,
      size: '18.7 MB',
      permissions: ['SELECT', 'INSERT'],
      rlsEnabled: true,
      description: 'Замовлення клієнтів',
    },
    {
      name: 'customers',
      records: 3421,
      size: '4.8 MB',
      permissions: ['SELECT'],
      rlsEnabled: true,
      description: 'Клієнти магазину',
    },
    {
      name: 'categories',
      records: 89,
      size: '125 KB',
      permissions: ['SELECT'],
      rlsEnabled: false,
      description: 'Категорії товарів',
    },
    {
      name: 'reviews',
      records: 2341,
      size: '3.1 MB',
      permissions: ['SELECT', 'INSERT', 'UPDATE'],
      rlsEnabled: true,
      description: 'Відгуки покупців',
    },
    {
      name: 'inventory',
      records: 8921,
      size: '5.6 MB',
      permissions: ['SELECT', 'UPDATE'],
      rlsEnabled: false,
      description: 'Складські залишки',
    },
    {
      name: 'carts',
      records: 1245,
      size: '890 KB',
      permissions: ['SELECT', 'INSERT', 'UPDATE', 'DELETE'],
      rlsEnabled: true,
      description: 'Кошики покупців',
    },
    {
      name: 'payments',
      records: 11234,
      size: '8.2 MB',
      permissions: ['SELECT'],
      rlsEnabled: true,
      description: 'Платежі',
    },
    {
      name: 'discounts',
      records: 234,
      size: '340 KB',
      permissions: ['SELECT'],
      rlsEnabled: false,
      description: 'Знижки та промокоди',
    },
    {
      name: 'shipping',
      records: 12456,
      size: '6.8 MB',
      permissions: ['SELECT', 'UPDATE'],
      rlsEnabled: true,
      description: 'Доставка замовлень',
    },
  ],
};
